server:
  port: 8081

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/inventorydb
    url: jdbc:postgresql://host.docker.internal:5432/inventorydb
    username: inventory
    password: inventory
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Kolkata
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    show-sql: false
    open-in-view: false
  jackson:
    time-zone: Asia/Kolkata
  cloud:
    config:
      enabled: false
  kafka:
    #bootstrap-servers: localhost:9092
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: import-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  tracing:
    sampling:
      probability: 1.0

notification:
  service:
    url: http://localhost:8083

logging:
  level:
    org.hibernate.SQL: ERROR